### ISSUE TITLE
Add support in SqlHydra CLI for mySQL

### ISSUE THREAD

**Issue by RJSonnenberg** [JordanMarr/SqlHydra#100]
I have a need for mySQL support. Up to now, I have manually written SqlHydra schema files for the few mySQL tables I need, but it is tedious work. I would much prefer to be able to use the CLI with mySQL.

**Comment by JordanMarr** [comment]
This looks great!
It needs a mysql docker container and some tests, but I’ll try to get it released as a beta so you can use it.

**Comment by JordanMarr** [comment]
Sorry for the delay. I haven’t forgotten about this, I’ve just been busier than usual the last couple weeks. Hopefully i can get a beta release out in the next day or so.

**Comment by RJSonnenberg** [comment]
@JordanMarr, looks like you added this in 2.6.0 prerelease and 2.5.3 that was just released? Should we close this issue now? Or did we need to keep it open since tests weren't written for the mySQL stuff?

**Comment by JordanMarr** [comment]
I decided to merge it even though the query side hasn’t been tested. That way it exists for anyone that wants to use it and possibly extend it.

I’m fine to close it.
