### ISSUE TITLE
Provider DB Type Attributes created even when provider_db_type_attributes is set to false

### ISSUE THREAD

**Issue by bnhoward** [JordanMarr/SqlHydra#102]
[general]
connection = "....................................."
output = "DbTypes.fs"
namespace = "Despatch.Command.Repository.DbTypes"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = false
table_declarations = false
[filters]
include = ["dbo/Del*","dbo/Disc*"]
exclude = []

With the above TOML config, the Provider DB Type Attributes are added to every property. Version 2.3.3 works as expected. The issue seems to appear in 2.4.0 up to current

**Comment by JordanMarr** [comment]
This should be fixed in v2.5.2.

**Comment by bnhoward** [comment]
Brilliant. Thanks Jordan
