### ISSUE TITLE
SqlHydra.Cli missing SQL Server `timestamp` data type mapping

### ISSUE THREAD

**Issue by tommi1hirvonen** [JordanMarr/SqlHydra#103]
SQL Server includes the `timestamp` data type, which is essentially a synonym for `rowversion`. Mapping for this data type is missing from [SqlServerDataTypes.fs](https://github.com/JordanMarr/SqlHydra/blob/main/src/SqlHydra.Cli/SqlServer/SqlServerDataTypes.fs), which means columns with data type `timestamp` are currently excluded from generated SqlHydra types and readers. `rowversion` is included in the data type mappings, and thus I believe `timestamp` should be implemented too.

**Comment by JordanMarr** [comment]
What data type does it map to?

**Comment by tommi1hirvonen** [comment]
I think it should actually map to `byte[]`, since it's the same as `rowversion`. I manually added the missing timestamp column to my generated SqlHydra type and reader as `byte[]`, and that seemed to work correctly. Also, according to [Microsoft's documentation](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings) the correct ClrType for `timestamp` is `Byte[]`.

This could potentially be as simple as just copying the `rowversion` mapping like this:

`SqlServerdatatypes.ds`
```fsharp
let supportedTypeMappings =
    [
        // ...
        "ROWVERSION", "byte[]", DbType.Binary, Some (nameof SqlDbType.Binary), nameof r.GetFieldValue
        // Added timestamp data type mapping
        "TIMESTAMP", "byte[]", DbType.Binary, Some (nameof SqlDbType.Binary), nameof r.GetFieldValue
        // ...
    ]
```

**Comment by JordanMarr** [comment]
Added to v2.5.3.
