### ISSUE TITLE
Use of DataTimeOffset means you must use SqlDataReader

### ISSUE THREAD

**Issue by isaacabraham** [JordanMarr/SqlHydra#14]
Dapper returns an `IDataReader` on it's extension method on top of the `SqlConnection`. Unfortunately, this does not contain the `GetDateTimeOffset` member that `SqlDataReader` does, so the generated SqlHydra code does not work.

Is there an alternative for the use of this member that would work with an `IDataReader`?

**Comment by JordanMarr** [comment]
Are you talking about the `HydraReader` constructor?
If so you could just cast the `IDataReader`:
https://github.com/JordanMarr/SqlHydra/blob/1dabec93fe9e0d8b8a06e3e900497e74e966edb5/src/SampleApp/DonaldExample.fs#L21

**Comment by isaacabraham** [comment]
The problem is that the `IDataReader` I'm using - Dapper's `ExecuteReader` extension method on top of a `SqlConnection` doesn't give back a `SqlDataReader` underneath the `IDataReader`.

**Comment by JordanMarr** [comment]
Interesting... Apparently the Dapper crew wrapped it in an extra layer, so I had to do this:

```F#
let getProductsWithThumbnailDapper(conn: SqlConnection) = task {
    use wrappedReader = conn.ExecuteReader("SELECT TOP 2 * FROM SalesLT.Product p WHERE ThumbNailPhoto IS NOT NULL")
    use reader = (wrappedReader :?> IWrappedDataReader).Reader :?> SqlDataReader
    let hydraReader = SalesLT.HydraReader(reader)
    return [ 
        while reader.Read() do
            hydraReader.Product.Read() 
    ]
}
```

**Comment by JordanMarr** [comment]
Unfortunately, it looks like if you are using vanilla Dapper, you will be stuck with `ExecuteReader` because it can be cast directly to an `IWrappedDataReader` which exposes a `.Reader` property that exposes the `SqlDataReader`.

I tried to get the `ExecuteReaderAsync` to work, but it returns a `DbWrappedDataReader` which, for some reason, they chose to make it internal. It keeps a private reference to the original `SqlDataReader` and implements `DbDataReader` and delegates it to its private `_reader`. This means that they have disallowed you from gaining access to the original `SqlDataReader`. 

OOP really does favor encapsulation and hiding!

**Comment by JordanMarr** [comment]
Actually, if you don't mind a small bit of reflection, you can still use `ExecuteReaderAsync`:

```F#

let reflectAsyncReader (dbWrappedReader: Common.DbDataReader) =
    let flags = System.Reflection.BindingFlags.NonPublic ||| System.Reflection.BindingFlags.Instance
    let field = dbWrappedReader.GetType().GetField("_reader", flags)
    field.GetValue(dbWrappedReader) :?> SqlDataReader

let getProductsWithThumbnailDapperAsync(conn: SqlConnection) = task {
    use! wrappedReader = conn.ExecuteReaderAsync("SELECT TOP 2 * FROM SalesLT.Product p WHERE ThumbNailPhoto IS NOT NULL")
    let hydra = SalesLT.HydraReader(wrappedReader |> reflectAsyncReader)
    return [ 
        while wrappedReader.Read() do
            hydra.Product.Read() 
    ]
}
```

**Comment by JordanMarr** [comment]
Was thinking about this and realized it is possible to use `ExecuteReaderAsync` with no reflection required:

```F#
let getProductsWithThumbnailDapperAsync(conn: SqlConnection) = task {
    use! wrappedReader = conn.ExecuteReaderAsync("SELECT TOP 2 * FROM SalesLT.Product p WHERE ThumbNailPhoto IS NOT NULL")
    use reader = (unbox<IWrappedDataReader> wrappedReader).Reader :?> SqlDataReader
    let hydra = SalesLT.HydraReader(reader)
    return [ 
        while wrappedReader.Read() do
            hydra.Product.Read() 
    ]
}
```

**Comment by isaacabraham** [comment]
Perfect, thanks.
