### ISSUE TITLE
Support for cancellation token in db operations

### ISSUE THREAD

**Issue by MargaretKrutikova** [JordanMarr/SqlHydra#19]
It seems like there is no support for passing cancellation token in async operations against `QueryContext`.
Do the native drivers have support for this? Would it be difficult to implement, what do you think?

**Comment by JordanMarr** [comment]
It probably would be fairly trivial to implement except that I am not yet sure where or how to pass a cancellation token to the underlying task.

**Comment by JordanMarr** [comment]
It looks like a `CancellationToken` can be passed to `ExecuteNonQueryAsync` and `ExecuteReaderAsync`.
So I imagine this being implemented in `QueryContext` as an `CancellationTokenSource option` property and a `UseTransaction` method that initializes it to `Some (new CancellationTokenSource())`. 
(Same design as the transaction feature.)

**Comment by MargaretKrutikova** [comment]
It's `CancellationToken` that you need to pass in `cmd.ExecuteReaderAsync` and `cmd.ExecuteScalarAsync`, `CancellationTokenSource` is created by the calling code. So I don't think we will need a property for `CancellationTokenSource ` or a `Cancel` method anywhere, since the calling code would have access to the original cancellation token source and will be able to cancel.

**Comment by MargaretKrutikova** [comment]
I was thinking an overload that takes an extra parameter for `CancellationToken`:
```fsharp
member this.GetReaderAsync<'T, 'Reader when 'Reader :> DbDataReader> (query: SelectQuery<'T>) = ...

member this.GetReaderAsync<'T, 'Reader when 'Reader :> DbDataReader> (query: SelectQuery<'T>, cancellationToken: CancellationToken) = ...
```
It seems to be the general pattern that `dotnet` libraries use to handle cancellation tokens, e.g. `HttpClient` and `GetAsync`, even `ExecuteReaderAsync` on the command. I do think it is a bit more difficult to use from `F#` where you would ideally want to pipe the query as the last parameter, but methods with curried arguments cannot be overloaded.

**Comment by JordanMarr** [comment]
That seems reasonable to add an overload that takes a tuple input. 
It would still be possible to use pipe operator if the cancel token was tupled along with the query.
