### ISSUE TITLE
sqlhydra-npgsql generation tool doesn't pick up "enum" columns

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [JordanMarr/SqlHydra#22]
Postgres has [enumerated datatypes](https://www.postgresql.org/docs/14/datatype-enum.html). The `sqlhydra-npgsql` generation tool doesn't seem to pick up these type of columns. I'd love it if it could at least think it's a column of type string.

**Comment by JordanMarr** [comment]
That sounds doable as long as there is a way to query the custom types.
It may be possible through the `NpgslConnection` `GetSchema` method; otherwise, we will need a query to get it.

**Comment by JordanMarr** [comment]
Oh I got it working already!

**Comment by JordanMarr** [comment]
SqlHyrda.Npgsql v0.800.1 is published.
Let me know if that causes any issues with inserts/updates.

**Comment by JordanMarr** [comment]
I assume this is resolved so closing.

**Comment by EverybodyKurts** [comment]
Sorry, I should have gotten back to you sooner... I get an `Npgsql.PostgresException` when attempting to insert a column:

```
Npgsql.PostgresException (0x80004005): 42804: column "color" is of type colors but expression is of type text
```

Basically, any string being inserted needs to be typecasted to the proper enum type like the following:

```
SELECT "blue"::colors;
```

**Comment by JordanMarr** [comment]
Any chance that it could it be a case-sensitivity issue?

**Comment by EverybodyKurts** [comment]
I think I would have gotten a different error had it been a case-sensitivity issue:

```pgsql
db=# CREATE TYPE colors AS ENUM ('red', 'green', 'blue');
CREATE TYPE

db=# SELECT 'Blue'::colors;
ERROR:  invalid input value for enum colors: "Blue"
LINE 1: SELECT 'Blue'::colors;

db=# SELECT 'blue'::colors;
 colors 
--------
 blue
(1 row)
```

**Comment by EverybodyKurts** [comment]
I don't know if this helps or not, but here's me creating a table and inserting a row from the psql command line:

```psql
db=# CREATE TABLE cars (color colors);
CREATE TABLE

db=# INSERT INTO cars (color) VALUES ('blue');;
INSERT 0 1

db=# SELECT * FROM cars;;
 color 
-------
 blue
(1 row)
```

**Comment by JordanMarr** [comment]
Ok I see what needs to happen:

```F#
        testTask "Insert Enum ADONET" {
            use conn = new Npgsql.NpgsqlConnection(connectionString)
            use cmd = conn.CreateCommand()
            cmd.CommandText <- 
                """
                INSERT INTO experiments.person (name, current_mood)
                VALUES (@name, @mood::mood)
                """
            let pName = cmd.CreateParameter()
            pName.ParameterName <- "@name"
            pName.Value <- "john doe"
            cmd.Parameters.Add pName |> ignore

            let pMood = cmd.CreateParameter()
            pMood.ParameterName <- "@mood"
            pMood.Value <- "happy"
            cmd.Parameters.Add pMood |> ignore

            conn.Open()

            let! results = cmd.ExecuteNonQueryAsync()

            Expect.isTrue (results > 0) ""
        }
```

**Comment by JordanMarr** [comment]
This is going to be really cool... 😎

**Comment by JordanMarr** [comment]
New release!
https://github.com/JordanMarr/SqlHydra/releases/tag/v0.810.0

You will need to manually register the generated enums with Npgsql (at least for now).

**Comment by JordanMarr** [comment]
Added a caveat that you may need to watch out for in the release notes.
