### ISSUE TITLE
MSSQL (Microsoft.Data.SqlClient): can't retrieve DateOnly

### ISSUE THREAD

**Issue by ntwilson** [JordanMarr/SqlHydra#25]
I'm using .net 6, SQL Hydra v. 1.0.0, and Microsoft.Data.SqlClient v. 4.1.0 to connect to an MSSQL database that includes some `DATE` columns.  SQL Hydra tries to use `System.DateOnly` for this, and it can write dates to the database just fine, but as soon as it tries to read a date from the database, it crashes in the SqlHydra-generated Reader code with
```
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'System.DateOnly'.
   at Microsoft.Data.SqlClient.SqlDataReader.GetFieldValueFromSqlBufferInternal[T](SqlBuffer data, _SqlMetaData metaData, Boolean isAsync)
   at Microsoft.Data.SqlClient.SqlDataReader.GetFieldValueInternal[T](Int32 i, Boolean isAsync)
   at Microsoft.Data.SqlClient.SqlDataReader.GetFieldValue[T](Int32 i)
   at MyProject.MyDatabase.dbo.get_MyColumn@537-2.Invoke(Int32 arg00) in C:\Git\MyRepo\MyProject\MyDatabase.fs:line 537
   at MyProject.MyDatabase.RequiredColumn`2.Read(FSharpOption`1 alias) in C:\Git\MyRepo\MyProject\MyDatabase.fs:line 11
   at MyProject.MyDatabase.dbo.MyTableReader.Read() in C:\Git\MyRepo\MyProject\MyDatabase.fs:line 542
```
It seems like `GetFieldValue<DateOnly>` doesn't work?  Can we just use `GetDateTime >> DateOnly.FromDateTime`?

**Comment by ntwilson** [comment]
I'm sorry I stated that backwards.  It can write a DateOnly to the database, but it can't read it from the database.  I'm going to edit the original text.

**Comment by JordanMarr** [comment]
That is surprising as there are some .NET 6 tests that query records with `DateOnly` properties.

**Comment by JordanMarr** [comment]
Yeah I did the same check and saw that there are no tests against that record. Adding a test now.
An immediate workaround would be to change that project to net5 so that `DateTime` is used instead of `DateOnly`.
But hopefully it won't take long to fix this.

**Comment by JordanMarr** [comment]
The test definitely failed! 😄

**Comment by ntwilson** [comment]
Thanks for the really fast turnaround on this, and for the awesome library for working with databases!  Really a big help!

**Comment by JordanMarr** [comment]
It looks like `DateOnly` updates/inserts are not yet supported in [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient/issues/1009). So it looks like `SqlHydra.Query` will need to handle conversion when creating parameters.

**Comment by JordanMarr** [comment]
SqlHydra.SqlServer v1.0.1 now generates a `GetDateOnly` extension method for .NET 6 and later.
SqlHydra.Query v1.0.1 now converts `DateOnly` properties to `DateTime` when creating insert/update parameters.

Let me know if you have any issues.
