### ISSUE TITLE
Table name collision when tables has the same name in different schemas (Postgres)

### ISSUE THREAD

**Issue by prekel** [JordanMarr/SqlHydra#3]
Thank you for support Postgres! 

But I cannot find how to select a specific schema for code generation. So, if there are tables with the same names in different schemas (in the screenshot on the right: `users` in `auth` and `users` in `public`), there will be collision and non-compilable generated code.

![image](https://user-images.githubusercontent.com/19646569/134388455-22600e32-8f06-490b-939d-11959393e8b2.png)

**Comment by JordanMarr** [comment]
I knew this was going to be a thing, but i didn’t think it would need a thing so quickly! 😅

But I should be able to fix it fairly easily by fully qualifying the generated lazy functions. (Currently they are named only after the table name which would cause a build error).

**Comment by JordanMarr** [comment]
Beta build pending...

**Comment by JordanMarr** [comment]
I have uploaded a new beta build for you to try that fully qualifies the generated `HydraReader` properties.
You should be able to update with this:

`dotnet tool update --local SqlHydra.Npgsql --version 0.500.0-beta.1`

**Comment by JordanMarr** [comment]
Hmm.. It looks I missed one thing in the fix...  incoming beta.2

**Comment by JordanMarr** [comment]
Fixed beta is uploaded:
`dotnet tool update --local SqlHydra.Npgsql --version 0.500.0-beta.2`

**Comment by JordanMarr** [comment]
FYI I just updated all the packages as v0.500.0 and rolled out this fix along with a few others:
https://www.nuget.org/packages?q=sqlhydra
