### ISSUE TITLE
`SqlHydra.ProviderDbType` Attribute requires SqlHydra.Query

### ISSUE THREAD

**Issue by JordanMarr** [JordanMarr/SqlHydra#42]
# Issue 
_(Raised by @isaacabraham)_

Table records generated by SqlHydra may contain `SqlHydra.ProviderDbType` attributes. 
This attribute is declared in the `SqlHydra.Query` package and is added to generated types to designate database specific parameter types for `SqlHydra.Query` to use when creating query parameters.

For example, NpgSql array types, json and jsonb types:

```F# 
module ext =
    type mood =
        | sad = 1
        | ok = 2
        | happy = 3

    [<CLIMutable>]
    type arrays =
        { id: string
          [<SqlHydra.ProviderDbType("Text,Array")>]
          text_array: string []
          [<SqlHydra.ProviderDbType("Integer,Array")>]
          integer_array: int [] }
```

The problem is that these attributes will cause a build error if the `SqlHydra.Query` package is not installed.
(At some point along the way, I think I forgot that some people only wanted to use the generated types without using `SqlHydra.Query`. But to be fair, the documentation to specify that the generated types can be used on their own)

# Solution 1
After generating the types for the first time, the command line wizard displays the following reminder to display the database specific provider package:
`AnsiConsole.MarkupLine($"[green]>[/] Please install the `{app.DefaultProvider}` NuGet package in your project.")`

A simple solution would be to also display a reminder to install `SqlHydra.Query`
The downside is that people would still be forced to add this as a dependency.

# Solution 2
Since the `SqlHydra.{Provider}` command line tools automatically add the generated types file to the .fsproj, it could also automatically add a reference to `SqlHydra.Query`.  (This may be a little too invasive though.)

# Solution 3
Maybe a more generic attribute from `System.ComponentModel` could be used instead?
This would remove the need to add `SqlHydra.Query` for those who do not wish to use it. But it would come at the expense of possibly misappropriating an existing attribute (which could also be later removed or changed).

# Solution 4
Add a new configuration option, `exclude_providerdbtype_attributes `, to the .toml config file under the `[readers]` section to allow users to exclude the `[<ProviderDbType>]` attributes used by `SqlHydra.Query`. (This will default to false if not present.)

Ex:

```
[general]
connection = "Server=localhost,12019;Database=AdventureWorks;User=sa;Password=Password#123;TrustServerCertificate=True"
output = "SqlServer/AdventureWorksNet5.fs"
namespace = "SqlServer.AdventureWorksNet5"
cli_mutable = true
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
exclude_providerdbtype_attributes = true
[filters]
include = [ "*" ]
exclude = [ "*/v*" ]
```

**Comment by JordanMarr** [comment]
Currently leaning towards "Solution 4" because this would be a non-breaking change to the TOML config that would allow users to have generated readers without generating the `SqlHydra.Query` integrations bits. 
If not present, `exclude_providerdbtype_attributes` would default to `false` since I think most people will use `SqlHydra.Query` in conjunction with their generated types (since it provides better query support and also adds insert, update and delete capabilities).

**Comment by JordanMarr** [comment]
@isaacabraham: 

SqlHydra.* v1.1.1 has just been published to fix this issue.
The CLI first-time run wizard has been greatly simplified: 

After getting the required fields (connection string, filename, namespace), it now only asks you to "Select a use case:"
with the following options:

* SqlHydra.Query integration (default)
* Other data library
* Standalone

It then sets all the configuration defaults accordingly (instead of asking you a bunch of random questions).
The second and third options will not generate the SqlHydra.Query specific attributes. 

You fix by either:
* deleting the generated .toml configuration file and then running `sqlhydra-mssql` (or whichever variant you are using) again.
* or by adding the following section to your existing .toml configuration file:
```toml
[sqlhydra_query_integration]
provider_db_type_attributes = false
```

**Comment by isaacabraham** [comment]
What is the difference between "Other data library" and "standalone"?
