### ISSUE TITLE
Add support for dotnet 7

### ISSUE THREAD

**Issue by EverybodyKurts** [JordanMarr/SqlHydra#44]
Currently only dotnet 5 and 6 are supported. I would love support for dotnet 7 :).

**Comment by JordanMarr** [comment]
Npgsql throws an error when setting up the enum mappings:

```F#
(ctx.Connection :?> Npgsql.NpgsqlConnection).TypeMapper.MapEnum<ext.mood>("ext.mood") |> ignore
```

It says it's no longer supported. 😞

**Comment by JordanMarr** [comment]
v1.1.0 is released with .NET 7 support. 🎉
