### ISSUE TITLE
Using a where clause with leftJoin

### ISSUE THREAD

**Issue by sydsutton** [JordanMarr/SqlHydra#54]
Hi Jordan,

First, thank you for the great product! 
Second, I was wondering if you have any suggestions for using a `where` clause after leftJoin'ing tables, like in the example below. When I try to dot into it with `.Value` in the where clause, I get this error: "Nested property value extraction is not supported in 'where' statements. Try manually unwrapping and passing in the value." I would appreciate any advice you might have. Thanks.
![image](https://user-images.githubusercontent.com/83406605/230625782-529f394a-b08b-40d4-a34f-6e7f702e9ac0.png)

**Comment by JordanMarr** [comment]
Hmm.. that looks like a regression bug.

**Comment by sydsutton** [comment]
Any suggestions and/or workarounds for the time being?

**Comment by JordanMarr** [comment]
For a workaround, you can use a manual query in conjunction with the generated reader types like this:


```F#
let getForecast (lower: DateTime, upper: DateTime) = task {
  let sql = """
    SELECT * FROM myschema.weather w
    WHERE     w.time >= @lower AND w.time <= @upper
      AND w.timestamp = (
        SELECT MAX(timestamp) FROM weather inner 
        WHERE inner.location = w.location AND inner.instrument = w.instrument AND inner.time =  w.time
    )
  """
  
  use conn = new NpgsqlConnection(DB.connectionString)
  do! conn.OpenAsync()
  use cmd = new NpgsqlCommand(sql, conn)
  cmd.Parameters.Add(NpgsqlParameter("lower", lower)) |> ignore
  cmd.Parameters.Add(NpgsqlParameter("upper", upper)) |> ignore
  let reader = cmd.ExecuteReader()
  let hydra = HydraReader(reader :?> NpgsqlDataReader)
  
  return [ while reader.Read() do hydra.``myschema.weather``.Read() ]
}
```

**Comment by JordanMarr** [comment]
Also, it appears you are still manually creating table bindings in your `Tables` module, but those are now generated for you as of v1.2.0:
https://github.com/JordanMarr/SqlHydra/releases/tag/v1.2.0

**Comment by JordanMarr** [comment]
I have made the fix, but I had to blow away my docker containers the other day, so it may take a few days for me to get set up again.

**Comment by sydsutton** [comment]
Thanks so much for the help, @JordanMarr !
