### ISSUE TITLE
Unable to use strings with isNotIn |<>| operation?

### ISSUE THREAD

**Issue by sachinshahredmane** [JordanMarr/SqlHydra#55]
Hello,

I have tried the following with both .NET 6 and .NET 7 and am receiving an error.

```fsharp
  selectTask HydraReader.Read (Create openContext) {
    for dl in dlTable do
      where (isNotIn dl.SystemName ignoreSystemNames)
      select (dl.DataListID, dl.Name, dl.SystemName) into selected
      mapList (//...
      )
  }
```

`dl.SystemName` is a `nvarchar(120)` column in the DB.  `ignoreSystemNames` has type `seq<string option>`. 

When I try to run the program, it fails immediately with the following exception.  My question is - is `isNotIn` supported with strings?  If so, how can I get it to work? 

```text
PS C:\projects2\graph\ConsoleApp1\bin\Debug\net6.0> .\mCaseDiagramGenerator.exe
Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$mCaseDiagramGenerator>.$com.znprojects.app.Program' threw an exception.
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (No mapping exists from object type Microsoft.FSharp.Core.FSharpOption`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] to a known managed provider native type.)))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (No mapping exists from object type Microsoft.FSharp.Core.FSharpOption`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] to a known managed provider native type.))
 ---> System.AggregateException: One or more errors occurred. (No mapping exists from object type Microsoft.FSharp.Core.FSharpOption`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] to a known managed provider native type.)
 ---> System.ArgumentException: No mapping exists from object type Microsoft.FSharp.Core.FSharpOption`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] to a known managed provider native type.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__207_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at com.znprojects.apps.DatabaseConnection.buildModel() in C:\projects2\mCase-graph\ConsoleApp1\DatabaseConnection.fs:line 117
   at <StartupCode$mCaseDiagramGenerator>.$com.znprojects.app.Program..cctor() in C:\projects2\mCase-graph\ConsoleApp1\Program.fs:line 9
   --- End of inner exception stack trace ---
   at com.znprojects.app.Program.main(String[] argv) in C:\projects2\mCase-graph\ConsoleApp1\Program.fs:line 193
```

**Comment by JordanMarr** [comment]
Can you give me more info about the type? It's hard to say without being able to see the properties being used in your query.

**Comment by sachinshahredmane** [comment]
Which types are you looking for? Happy to provide more information.  Also, I should note that I am using SQL Server as the database, not sure if that affects the behavior or not. 

Here is the definition of the `ignoreSystemNames` (it's a constant that is passed in elsewhere): 

```fsharp
let DefaultIgnoreListSystemNames =
  [ "TODO"
    "DataMover"
    "DataFieldMover"
    "AnalysisReference"
    "CHECKINOPTIONS"
    "UploadDataList"
    "UploadErrorDataList" ]
  |> List.map (fun sn -> sn.ToUpper())
  |> List.map Option.Some
```

Here is the column in my schema:
![image](https://user-images.githubusercontent.com/29237818/230938400-1c5503f4-0aeb-409d-b4ec-546305e7db4f.png)

Here is the exact query that it is running:

```fsharp
let getLists ignoreSystemNames =
  selectTask HydraReader.Read (Create openContext) {
    for dl in dlTable do
      where (dl.SystemName |<>| ignoreSystemNames)
      select (dl.DataListID, dl.Name, dl.SystemName) into selected

      mapList (
        let dlid, n, sn = selected

        { DataListID = dlid
          Name = n
          SystemName = (Option.defaultValue "" sn).ToUpper()
          Category = ListCategory.Unknown
          TopLevel = false }
      )
  }
```

**Comment by sachinshahredmane** [comment]
I should note, my workaround right now is to get all values from the DB since I want the majority (minus the 7 in my list), then filter on the results of the Task.  However, I will definitely keep the workaround in mind (and may end up implementing it anyway).

**Comment by JordanMarr** [comment]
It looks like `dl.SystemName` is an `option` type, which explains why you are mapping your list to `Option.Some`.
`|<>|` / `isNotIn` doesn't know how to deal with a list of `option` values (or at least not at the moment).

Try using `where (dl.SystemName.Value |<>| ignoreSystemNames)` (and not mapping the list to `option` values).

There is a similar bug from a few days ago around option types that I was just about to release a fix for today, and this looks like it may be the same bug.

**Comment by sachinshahredmane** [comment]
You're absolutely right, I was just about to comment that another query where the column is not-nullable works as expected (`string !<>| stringList`).  

I will try to force the `.Value` and see if that fixes it for now.  Thank you!

**Comment by JordanMarr** [comment]
Please let me know if that works for you.

**Comment by sachinshahredmane** [comment]
Using `.Value` has fixed the issue for now.

**Comment by sachinshahredmane** [comment]
For now, I'm filtering outside the CE and that, of course, works.

**Comment by JordanMarr** [comment]
Are you using the latest SqlHydra.Query v2.0.1?

**Comment by sachinshahredmane** [comment]
I am.  I found the issue.

If I use this, it works: `dl.SystemName.Value`.

If I try to do something with the string, it fails: `dl.SystemName.Value.ToUpper()`.

I changed the DB to use an case-insensitive collation and that solved the problem.  I believe this issue can be closed now.

**Comment by JordanMarr** [comment]
Thanks for the update.
