### ISSUE TITLE
`where` clause with direct boolean column does not work

### ISSUE THREAD

**Issue by jwosty** [JordanMarr/SqlHydra#61]
It would be nice if you could write the following (where `is_latest` is a boolean column):

```fsharp
selectAsync {
    for foo in someTable do
    where foo.is_latest
    select foo
    tryHead
}
```

instead, you have to manually check for `true`:

```fsharp
selectAsync {
    for foo in someTable do
    where (foo.is_latest = true)
    select foo
    tryHead
}
```

**Comment by JordanMarr** [comment]
I have had the same thought as well!

**Comment by JordanMarr** [comment]
Would also need to handle `bool option` fields using `.Value` property.

**Comment by JordanMarr** [comment]
Started looking into the implementation. Logging a few notes here so I don't forget.

* Should handle the following cases:
  * `bool` true - `where user.TermsAccepted`
  * `bool` false - `where (not user.TermsAccepted)`
  * `bool option` true - `where user.TermsAccepted.Value`
  * `bool option` false - `where (not user.TermsAccepted.Value)`

**Comment by JordanMarr** [comment]
Released!
https://github.com/JordanMarr/SqlHydra/releases/tag/v2.1.0

**Comment by jwosty** [comment]
I think the implementation sounds sane. If I were using a `not` on a `bool option`, I'm not actually sure what I would expect it to do, so I feel anything is fine. I would probably tend to be explicit if I wanted different behavior. It would probably be good to call out this edge case in the docs.

In an ideal world, it would arguably even emit a warning. Perhaps a SqlHydra analyzer would be useful when that SDK drops someday!
