### ISSUE TITLE
Fails to insert jsonb values in Postgres

### ISSUE THREAD

**Issue by MargaretKrutikova** [JordanMarr/SqlHydra#7]
We have a table with a field of type `jsonb`, which becomes `string` in the generated type, but it doesn't seem to work when inserting a string with the json format, the exception I get is:
```
Npgsql.PostgresException (0x80004005): 42804: column "test" is of type jsonb but expression is of type text
Exception data:
    Severity: ERROR
    SqlState: 42804
    MessageText: column "test" is of type jsonb but expression is of type text
    Hint: You will need to rewrite or cast the expression.
    Position: 97
    File: parse_target.c
    Line: 588
    Routine: transformAssignedExpr
```
when trying to insert `"""{"publisher": "test"}"""`.
Would you be able to help with this?

**Comment by JordanMarr** [comment]
What should happen during the insert for the jsonb field? 
Does the string need to be transformed before being inserted?

**Comment by JordanMarr** [comment]
There are two ways I can think of to do this.

Option 1 would involve creating many provider specific versions of SqlHydra.Query. I would prefer to avoid this option.

Option 2 would involve using reflection to set provider specific type mapping enum:
* Generated table record properties could be decorated with a metadata attribute that preserves their mapped type as a string: Ex: `[<Parameter("NpgsqlDbType.Jsonb")>]. 
* BuildCommand would use some reflection to check for existence of attribute, and if found, use reflection to assign parameter type.

**Comment by MargaretKrutikova** [comment]
How do I run the tests for `postgres`? Specifically `Tests/Npgsql`.

**Comment by JordanMarr** [comment]
The most simple way if you are using vscode is to `dotnet run` the Tests project which will run all tests.
If you want to only run the postgres tests then you will need to change the `[<Tests>]` attribute to `[<FTests>]` for the files that you want to focus.

**Comment by MargaretKrutikova** [comment]
I started looking into this issue, and while I am able to generate the attribute as you suggested, I am not sure I understand how to access this value inside `BuildCommand` and parse it into the actual value e.g. `NpgsqlDbType.Jsonb` since we are using `string` inside the attribute. 
Can we have some kind of DU as the attribute value? Like
```
type DbColumnType =
    | Npgsql of NpgsqlDbType
    | Mssql of ....
```
Although this would have to be inside `Domain.fs` as part of the `Column`, and I assume we don't want to introduce any dependencies on the database type inside the domain.

**Comment by JordanMarr** [comment]
The technique would be the same one used by SQLProvider to do load provider-specific objects via reflection.

* first they create a new [parameter](https://github.com/fsprojects/SQLProvider/blob/da11e4bb621db34b013feb48a3363bfd75668a68/src/SQLProvider.Runtime/Providers.Postgresql.fs#L55) object. (We already have one, so no need to create one via Activator)
* But we would need the `dbTypeSetter` to set the `NpgsqlDbType`.
* Since it’s an enum value, we might need to store the value as an `int` instead of a `string`.

**Comment by MargaretKrutikova** [comment]
Ok, I got the idea, and all the reflection business seems to work. The problem I am having now is how to match the field attributes to the corresponding parameter in `compiledQuery.NamedBindings` inside `BuildCommand`, because all the information about the record fields inside `Query` is lost and all the parameters are called `@p0` etc. Do you have any on how to do it?

**Comment by MargaretKrutikova** [comment]
I am not sure we can rely on the order of the parameters since `NamedBindings` in the compiled query is of type `Dictionary` where the order is not guaranteed, right? It would be great if instead of `@p0` we could get the actual column names from `SqlKata`, but it doesn't seem like it is going to be implemented, though the issue for [named parameters](https://github.com/sqlkata/querybuilder/issues/168) exists and is closed.

**Comment by MargaretKrutikova** [comment]
Oh, that's genius 😄 I almost made it work with this new suggestion ... will need to clean up the mess and open a PR in the beginning of the week. Yeah, I am enjoying the process, thanks for the help!
