### ISSUE TITLE
Creating sqlhydra file updates the wrong .fsproj file

### ISSUE THREAD

**Issue by Janna112358** [JordanMarr/SqlHydra#75]
### Issue

I work with several F# solutions that have a file structure along the lines of:

```txt
.
├── README.md
├── Build.fsproj
├── ...
├── server
│   ├── server.fsproj
│   ├── ...
│   └── Common
│      └── Db.fs
├── tests
│   ├── tests.fsproj
│   └──...
 ```
 
 I use sqlhydra to generate the file at ./server/Common/Db.fs, and write instructions in the README for other developers to do the same (after schema changes) from the repo root. I've noticed that sqlhyra automatically adds en entry for the generated file in the `Build.fsproj`. However, I need the file to be compiled as part of the server project. (Moving the entry to `server.fsproj` is a one-time thing; sqlhydra changing `Build.fsproj` on every use is the main thing I would like to be able to change.)
 
 ### Ideas
 
 I would love to be able to pass a `--project /path/to/project.fsproj` argument to the client tool, or store the target project as a configuration in the .toml file. Alternatively, an option to simply turn off the tool updating any .fsproj file would also help a lot.

**Comment by JordanMarr** [comment]
That sounds like a good addition.

**Comment by JordanMarr** [comment]
[v2.3.1](https://www.nuget.org/packages/SqlHydra.Cli) has been published.

**Comment by Janna112358** [comment]
Thank you, amazing! I'm using it right away :)

**Comment by JordanMarr** [comment]
If you are feeling ambitious, you are certainly welcome to submit a PR. 
If not, I don't mind doing it. 

There is a "devcontainer" setup that is supposed to magically spin up a vs code environment, but TBH, I've had issues with it recently. I think it may need to TLC to get it working.
So, I would recommend just manually spinning up the docker containers using `docker-compose up`.

**Comment by Janna112358** [comment]
Great! I've tested 2.3.2 and indeed what I do is:

- I run the cli from the root of the repository, with option `--project path/to/targetProject.fsproj`
- Instead of giving the absolute path for the sqlhydra output file, I now give it a path relative to the `targetProject.fsproj`
- Now the output file is put in the targetProject AND the compiler entry in `targetProject.fsproj` uses the relative path as expected :)

I've checked it with and without the output file and/or the compiler entry in `targetProject.fsproj` already existing, and all good!

Thanks very much for this, it makes my life just a little bit easier 🙏
