### ISSUE TITLE
Conversion from Task to Async to Task

### ISSUE THREAD

**Issue by stoft** [JordanMarr/SqlHydra#8]
Hello!
I noticed that there is a conversion from `Task` to `Async` to `Task` here: https://github.com/JordanMarr/SqlHydra/blob/7d24b1d1b8266786bb3e03a17f3e6b214e128a59/src/SqlHydra.Query/QueryContext.fs#L127

and here:
https://github.com/JordanMarr/SqlHydra/blob/7d24b1d1b8266786bb3e03a17f3e6b214e128a59/src/SqlHydra.Query/QueryContext.fs#L136

Just for my understanding, is this double conversion really necessary? And possibly correlated, why choose to return a  Task and not an Async?

Cheers!

**Comment by stoft** [comment]
Is this different from accessing `Task.Result`? ["If the Result property is accessed before the computation finishes, the property blocks the calling thread until the value is available."](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming#creating-and-running-tasks-explicitly)

**Comment by JordanMarr** [comment]
Yes, this approach is actually asynchronous, whereas `Task.Result` would not be because it would block (wait) for the database response before returning the result.

**Comment by stoft** [comment]
And thus it's up to the caller of `InsertAsync` to block or not? For lack of a `Task.map` or similar (which a task builder lib or v6 would provide). Makes sense. 😄

**Comment by stoft** [comment]
Thank you for the insights, very helpful for my understanding. 🙂
