### ISSUE TITLE
Best practice for multiple environments and the config.toml file

### ISSUE THREAD

**Issue by kaeedo** [JordanMarr/SqlHydra#81]
Hello. I've been trying to figure out best practices for dealing with multiple environments and checking in the config.toml file. Specifically, I don't want to expose the postgres connection string with password by checking it into source control. Is there some best practice for reading it in from `dotnet user-secrets` or env vars, or having an override such as `config.local.toml` which would get .gitignored?

Thanks

**Comment by JordanMarr** [comment]
Having a built-in way to hide connection strings that contain a password would be a great feature. There is currently not a built-in way to do this. For a temporary solution, you would probably need to manually add the toml file(s) to your gitignore.

**Comment by kaeedo** [comment]
Thanks. That's what i've been doing now. Just as another suggestion, maybe you could pass in the connectionString/password via a CLI argument. something like `dotnet sqlhydra npgsql --connection-string "My connection string"`

**Comment by JordanMarr** [comment]
That seems like a good approach. Is the idea that you would use a variable in the command line for the password?

Like this:
```bat
"Server=localhost,12019;Database=AdventureWorks;User=sa;Password=$(Password);TrustServerCertificate=True"
```

**Comment by kaeedo** [comment]
Basically that. Then you can use your favorite CLI tools to pass the connection string via STDOUT or similar

`dotnet sqlhydra npgsql --connection-string $CONNSTR`

**Comment by JordanMarr** [comment]
SqlHydra.Cli v2.3.3 is published with new arg:

```F#
Input.OptionMaybe<string>(["-cs"; "--connection-string"], "The DB connection string to use. This will override the connection string in the toml file.")
```

**Comment by JordanMarr** [comment]
I should probably document the various command line arguments that have been added.
But then again, it uses FSharp.SystemCommandLine, so it is kind of self documenting. 
¯\\_(ツ)_/¯

**Comment by kaeedo** [comment]
Cool. Thanks much
