### ISSUE TITLE
Public Schema Not Properly Escaped for NpgSQL in v2.4+

### ISSUE THREAD

**Issue by devinlyons** [JordanMarr/SqlHydra#93]
v2.3 generates a line of code with the following valid syntax:

``` fsharp
let lazypublicmigration = lazy (``public``.Readers.migrationReader (reader, buildGetOrdinal 3))
```

v2.4 generates this invalid code:

``` fsharp
let ``lazy``public``migration`` = lazy (``public``.Readers.migrationReader(reader, buildGetOrdinal 3))
```

v2.5 generates this invalid code:

``` fsharp
let ``lazy``public``migration`` = lazy (``public``.Readers.migrationReader(reader, buildGetOrdinal typeof<public.migration>))
```

NOTE: the syntax for `typeof<public.migration>` should be `typeof<``public``.migration>`

**Comment by JordanMarr** [comment]
Looks like that bug that resulted from the total rewrite of the gen code. Apparently, none of my test databases have a `public` schema that triggers this condition.

**Comment by JordanMarr** [comment]
SqlHydra.Cli v2.5.1 has been released with the fix.

Looks like I had it completely backwards:
![image](https://github.com/JordanMarr/SqlHydra/assets/1030435/ebf63657-c436-45d9-a27e-859103861deb)
