### ISSUE TITLE
Query with `leftJoin` breaks in v2.5.0

### ISSUE THREAD

**Issue by stoft** [JordanMarr/SqlHydra#94]
The following `leftJoin` query works in v2.4.1 but generates an error in v2.5.0:

**Query:**

```fsharp
selectTask HydraReader.Read (Create openContext) {
    for i in insurance_policies do
        where (i.id = id)
        join ic in insurance_companies on (i.insurance_company_id = ic.id)
        leftJoin ip in insurance_policy_properties on (i.id = ip.Value.insurance_policy_id)
        select (i.id, ic.name, i.product_variant, i.insurance_type_id, ip)
})
```

**Error:**
> System.NullReferenceException: Object reference not set to an instance of an object.

If we remove the `leftJoin` the query works. We're using Postgres (Npgsql.FSharp v5.7.0).

**Comment by JordanMarr** [comment]
There is a v2.5.1 patch released last week that may fix this. Please try it and let me know.

**Comment by stoft** [comment]
Sorry, we completely missed there was a 2.5.1. Which works. :)

**Comment by JordanMarr** [comment]
Btw, you can now pass `openContext` instead of `Create openContext` and it will implicitly convert it for you:

// Old
```F#
selectTask HydraReader.Read (Create openContext) {
```

// New
```F#
selectTask HydraReader.Read openContext {
```

Same with shared context:

// Old
```F#
selectTask HydraReader.Read (Shared ctx) {
```

// New
```F#
selectTask HydraReader.Read ctx {
```
