### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by jwosty** [JordanMarr/SqlHydra#99]
It would be nice-to-have if SqlHydra supported other array types (specifically I'm using the npgsql adapter). Note that `bytea` is already supported

Example schema:

```sql
CREATE TABLE foo
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    some_data text[] NOT NULL
);
```

Not a showstopper; obviously the workaround is just to normalize this kind of data into actual relations.

**Comment by JordanMarr** [comment]
Hmm... I thought it already did support postgres arrays. 
For example, in npgsql, your generated code should include array types:
https://github.com/JordanMarr/SqlHydra/blob/3525f6a2839e5c839417f447c83669fb24f495fd/src/Tests/Npgsql/AdventureWorksNet8.fs#L7523

**Comment by JordanMarr** [comment]
Also, the npgsql generation code should add array mappings programmatically:
https://github.com/JordanMarr/SqlHydra/blob/3525f6a2839e5c839417f447c83669fb24f495fd/src/SqlHydra.Cli/Npgsql/NpgsqlDataTypes.fs#L59

**Comment by jwosty** [comment]
Oh, looks like I was using an older version of sqlhydra CLI in this particular project without realizing it. Yup, confirming that this does work fine.
